69 Update data with `adae` changes
insightsengineering/scda.2022 pull request #70
Opened 2022-09-08 14:06 UTC by edelarua

Closes #69

2022-09-09 00:23 UTC, codesformochi requested changes

2022-09-09 00:23 UTC, codesformochi commented on data_raw/rcd.R
> +  "2022_06_27" = "33ab12d00478c72b74d82150dbbd748af196dccf"
is this the right commit? i checked the logs of the RCD/main for the issue and it has a different commit in the log (please let me know if i'm looking at the log wrong).
<img width="764" alt="Screen Shot 2022-09-08 at 5 19 24 PM" src="https://user-images.githubusercontent.com/39424598/189247642-a5eaf6b1-52f4-493d-96ed-3bb12f467690.png">

2022-09-09 00:23 UTC, codesformochi commented on data_raw/rcd.R
> +  "2022_06_27" = "33ab12d00478c72b74d82150dbbd748af196dccf"
this is my only comment! the rest looks good!

2022-09-12 23:39 UTC, shajoezhu commented
Hi  @edelarua @codesformochi , is this good to go? :)

2022-09-13 00:24 UTC, edelarua commented
> Hi @edelarua @codesformochi , is this good to go? :)

@shajoezhu this should be good to go, but we could add in the updates to adsl as well if we wait and merge https://github.com/insightsengineering/random.cdisc.data/pull/200 first.

2022-09-13 01:10 UTC, shajoezhu commented
Brilliant! Thanks @edelarua ! ok, let's wait for https://github.com/insightsengineering/random.cdisc.data/pull/194 as well then. we can check in on this again tonight

2022-09-13 12:31 UTC, shajoezhu commented
hi @edelarua , would you mind do another update on this please

<img width="1335" alt="image" src="https://user-images.githubusercontent.com/3692541/189901532-f95e2307-2786-4d8a-bf1d-c6fed2dd58c0.png">

https://github.com/insightsengineering/random.cdisc.data/commits/main

to e96be720f5828bbe869325e9fc15e227f998f3dd

2022-09-13 13:02 UTC, shajoezhu approved these changes
lgtm! Thanks @edelarua

2022-09-13 14:22 UTC, merged